import json
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

# Load the data generated by your detector
filename = "roc_data_robust_three_faults.json"  

try:
    with open(filename, "r") as f:
        data = json.load(f)
        
    y_true = data["y_true"]
    y_scores = data["y_score"]

    # Calculate ROC curve points
    fpr, tpr, thresholds = roc_curve(y_true, y_scores)
    roc_auc = auc(fpr, tpr)

    # Plot the curve
    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--') 
    
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate (Recall)')
    plt.title('Receiver Operating Characteristic (ROC)')
    plt.legend(loc="lower right")
    plt.grid(True)
    
    plt.savefig("graph_roc_curve.png")
    plt.show()

except FileNotFoundError:
    print(f"Error: Could not find {filename}")